// Maps the Banani design source's `<Icon i="kebab-name" />` convention onto
// real lucide-react components. Named imports only (not the full icon map)
// so unused icons don't ship in the bundle — extend ICONS as new Banani
// screens introduce new icon names.
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BarChart2,
  Bell,
  BellOff,
  BookOpen,
  Calendar,
  CalendarPlus,
  CalendarX,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  EyeOff,
  FileText,
  FileUp,
  Flag,
  Globe,
  GraduationCap,
  Info,
  LayoutDashboard,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pencil,
  Phone,
  Plus,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sliders,
  Smartphone,
  Star,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'bar-chart-2': BarChart2,
  bell: Bell,
  'bell-off': BellOff,
  'book-open': BookOpen,
  calendar: Calendar,
  'calendar-plus': CalendarPlus,
  'calendar-x': CalendarX,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  // lucide-react dropped brand icons (Chrome, Facebook, …) — Banani's
  // "Continuer avec Google" button used i="chrome"; Globe is the closest
  // neutral stand-in until a real Google "G" mark is wired.
  chrome: Globe,
  clock: Clock,
  'credit-card': CreditCard,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'file-text': FileText,
  'file-up': FileUp,
  flag: Flag,
  'graduation-cap': GraduationCap,
  info: Info,
  'layout-dashboard': LayoutDashboard,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  paperclip: Paperclip,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  search: Search,
  send: Send,
  settings: Settings,
  'shield-check': ShieldCheck,
  sliders: Sliders,
  smartphone: Smartphone,
  star: Star,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  x: X,
};

interface IconProps {
  i: string;
  size?: number;
  className?: string;
}

export function Icon({ i, size = 16, className }: IconProps) {
  const LucideComponent = ICONS[i];
  if (!LucideComponent) return null;
  return <LucideComponent size={size} className={className} aria-hidden="true" />;
}
